export interface DocChunk {
  id: string;
  section: string;
  text: string;
}

export const DUMMY_DOC: DocChunk[] = [
  { id: '1', section: 'Overview', text: "ARC is a mobile-first audio review tool for Google Docs. It lets a user listen to a document, interrupt naturally, speak feedback, and later sync that feedback back into the source document as structured comments. The product is aimed at people who review written work while walking, commuting, or otherwise away from a desk.\n\nThe core idea is simple: turn document review into a voice-first workflow. Instead of sitting in front of a laptop and typing comments into the margin, the user listens to a document in sequence and speaks comments as thoughts occur." },
  { id: '2', section: 'User Problem', text: "Many writing and review workflows assume the user is stationary, looking at a screen, and willing to stop to type. This creates friction for people who think more clearly while moving or who want to review long documents during otherwise idle time.\n\nTraditional text-to-speech tools solve only part of the problem. They can read a document aloud, but they do not usually let the user interrupt naturally, dictate feedback, and keep those comments tied to the relevant part of the source material.\n\nThere is also a workflow gap between passive listening and active editing. Users may listen to a draft on the move, record voice notes elsewhere, and later manually translate those notes into document comments. This adds duplication and weakens the connection between what was heard and what was said." },
  { id: '3', section: 'Proposed v1 Workflow', text: "The user pastes a Google Doc link into ARC. The app parses the document into small chunks and reads each chunk aloud using a conversational AI voice. While the text is being read, the user can interrupt by speaking a trigger phrase such as 'wait' or 'add a comment'.\n\nOnce interrupted, ARC pauses playback and captures the user's spoken feedback. After the user finishes speaking, ARC confirms that the comment has been saved and resumes reading from the correct place.\n\nAt the end of a review session, ARC exports the captured feedback as structured comment data. This data includes the relevant text quote, chunk index, transcript, and timestamp. A follow-on sync process can then attempt to push those comments back to the original Google Doc." },
  { id: '4', section: 'v1 Scope', text: "The first release should focus on the core reading and feedback loop rather than trying to solve the entire Google Docs editing experience. The main goal is to make the interruption and capture workflow feel smooth, dependable, and mobile-friendly.\n\nIn scope for v1 are: loading a Google Doc, chunking text, audio playback, natural interruption, spoken comment capture, local session persistence, and structured export for later sync.\n\nOut of scope for v1 are: perfect inline anchored Google Docs comments during live playback, multi-user collaboration, advanced analytics, broad document format support, and support for every complex object type." },
  { id: '5', section: 'Feature Priorities', text: "The following is a breakdown of feature priorities for ARC v1.\n\n| Feature | Priority | Notes |\n|---------|----------|-------|\n| Read document aloud | Must have | Core value of the product |\n| Voice interruption | Must have | Essential for natural review |\n| Comment capture and resume | Must have | Needed for a coherent workflow |\n| Local persistence | Should have | Important for real mobile use |\n| Google Docs import | Should have | Important, but depends on integration reliability |\n| Native anchored inline comments | Could have | Valuable, but risky because of API limitations |\n| Broader file type support | Could have | Useful later, not essential for launch |" },
  { id: '6', section: 'Risks and Assumptions', text: "The biggest product risk is that users may expect ARC to behave exactly like Google Docs commenting, even though the sync layer may initially rely on structured exports or less direct comment insertion methods.\n\nA second risk is performance. Real-time voice interaction, long document handling, and mobile browser constraints may introduce latency or instability if the implementation is too ambitious too early.\n\nA key assumption is that users are willing to trade some precision in live comment placement for a much more convenient review workflow. Another assumption is that people reviewing documents in motion will accept a chunked reading model rather than full visual control at all times." },
  { id: '7', section: 'Early Business Rationale', text: "The first target users are likely to be writers, researchers, consultants, product managers, and designers who review their own drafts regularly. A secondary audience may include people with accessibility needs or users who prefer listening and speaking over typing.\n\nARC could begin as a focused productivity tool with a freemium model. A free tier might include limited review minutes or a small number of synced comments per month, while a paid plan could unlock longer sessions, better exports, and more reliable sync workflows.\n\nThere is also an opportunity to position ARC as both a utility and a demonstration of voice-first interaction design. That could make it useful not only as a product, but also as a portfolio-quality example of applied product thinking." },
  { id: '8', section: 'Success Metrics', text: "In the short term, success should be measured by workflow completion rather than scale. A useful early benchmark would be whether a user can review a short document, interrupt multiple times, and finish with a set of comments that still make sense when mapped back to the source.\n\nPossible early metrics include: average review session length, number of comments captured per session, successful resume rate after interruption, session recovery after app interruption, and percentage of exported comments that can be reconciled to source text." },
  { id: '9', section: 'Open Questions', text: "Should ARC aim to feel like a specialised productivity tool for writers, or should it position itself more broadly as a voice-first layer for document workflows?\n\nHow much imperfection in Google Docs comment placement will users tolerate if the core listening and speaking experience is strong?\n\nWould users prefer a very simple experience focused only on Google Docs, or would broader support for Word, PDFs, and notes be more important early on?" }
];
